Tarea 1 

Integrantes

Javier Vega 
Erick Calvo


1.Primer estandarizar usando la libreria 

In [7]:

#importar todas las librerias requeridas
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler, MinMaxScaler
import torch 

import os
os.environ["KMP_DUPLICATE_LIB_OK"]="TRUE"

#cargar los datos 
path = "daily-min-temperatures.txt"

datos_df = pd.read_csv(path, delimiter=',')

#verificar los datos cargados
print(datos_df)

print(datos_df.columns)

#selecionar datos a estadarizar-normalizar
np_datos = np.array(datos_df.iloc[:,-1:])
print(np_datos)

            Date  Temp
0     1981-01-01  20.7
1     1981-01-02  17.9
2     1981-01-03  18.8
3     1981-01-04  14.6
4     1981-01-05  15.8
...          ...   ...
3645  1990-12-27  14.0
3646  1990-12-28  13.6
3647  1990-12-29  13.5
3648  1990-12-30  15.7
3649  1990-12-31  13.0

[3650 rows x 2 columns]
Index(['Date', 'Temp'], dtype='object')
[[20.7]
 [17.9]
 [18.8]
 ...
 [13.5]
 [15.7]
 [13. ]]


In [10]:
#Estandarización Automática

scaler = StandardScaler()
scaler.fit(np_datos)

datos_estandarizados = scaler.transform(np_datos)

print(datos_estandarizados)

[[2.33888328]
 [1.65113873]
 [1.87219948]
 ...
 [0.5703973 ]
 [1.11076801]
 [0.44758577]]


In [11]:
#Normalización Automática

scaler = MinMaxScaler()
scaler.fit(np_datos)

datos_normalizados = scaler.transform(np_datos)

print(datos_normalizados)

[[0.78707224]
 [0.68060837]
 [0.7148289 ]
 ...
 [0.51330798]
 [0.59695817]
 [0.49429658]]


In [6]:
#Estandarización manual:

estandarización_manual = (np_datos - np_datos.mean()) / np_datos.std(ddof=1)

print(estandarización_manual)

[[2.33856287]
 [1.65091253]
 [1.871943  ]
 ...
 [0.57031915]
 [1.11061584]
 [0.44752445]]


In [12]:
#Normalización manual:

normalización_manual = (np_datos - np_datos.min()) / (np_datos.max() - np_datos.min())

print(normalización_manual)

[[0.78707224]
 [0.68060837]
 [0.7148289 ]
 ...
 [0.51330798]
 [0.59695817]
 [0.49429658]]
